USE [master]
GO

/****** Object:  Database [sanctuary]    Script Date: 20/03/2022 18:05:11 ******/
CREATE DATABASE [sanctuary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sanctuary', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\sanctuary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sanctuary_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\sanctuary_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sanctuary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sanctuary] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sanctuary] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sanctuary] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sanctuary] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sanctuary] SET ARITHABORT OFF 
GO

ALTER DATABASE [sanctuary] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sanctuary] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sanctuary] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sanctuary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sanctuary] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sanctuary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sanctuary] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sanctuary] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sanctuary] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sanctuary] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sanctuary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sanctuary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sanctuary] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sanctuary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sanctuary] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sanctuary] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sanctuary] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sanctuary] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sanctuary] SET  MULTI_USER 
GO

ALTER DATABASE [sanctuary] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sanctuary] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sanctuary] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sanctuary] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sanctuary] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sanctuary] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sanctuary] SET QUERY_STORE = OFF
GO

ALTER DATABASE [sanctuary] SET  READ_WRITE 
GO

